name: flutter_movie
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio:
  cupertino_icons: ^1.0.2
  lottie: ^1.4.2
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  get_it: ^7.2.0
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie.json